# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\austc\Documents\GitHub\OrpheusElectronics\Psoc Arm\I2C_Master_High_Level01.cydsn\I2C_Master_High_Level01.cyprj
# Date: Thu, 28 Mar 2019 20:02:47 GMT
#set_units -time ns
create_clock -name {mI2C_SCBCLK(FFB)} -period 625 -waveform {0 312.5} [list [get_pins {ClockBlock/ff_div_2}]]
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {mI2C_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 15 31} [list]


# Component constraints for C:\Users\austc\Documents\GitHub\OrpheusElectronics\Psoc Arm\I2C_Master_High_Level01.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\austc\Documents\GitHub\OrpheusElectronics\Psoc Arm\I2C_Master_High_Level01.cydsn\I2C_Master_High_Level01.cyprj
# Date: Thu, 28 Mar 2019 20:02:43 GMT
