/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "RX.h"
#include "RX_aliases.h"
#include "TX.h"
#include "TX_aliases.h"
#include "CAN.h"
#include "TX_EN.h"
#include "TX_EN_aliases.h"
#include "ADC.h"
#include "LCD.h"
#include "Switch1.h"
#include "Switch1_aliases.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "PWM.h"
#include "Clock_1.h"
#include "PWM_OUT.h"
#include "PWM_OUT_aliases.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "PSoC3_8051.h"
#include "cy_em_eeprom.h"

/*[]*/

